version: '3.8'

services:
  apiserver:
    build: ./apiserver
    networks:
      - backend-network

  web-front:
    build: ./web-front
    ports:
      - "80:80"
    networks:
      - backend-network
      - client-network
    depends_on:
      - apiserver

  clicker:
    build: ./clicker
    networks:
      - client-network
    depends_on:
      - web-front

networks:
  backend-network:
  client-network:
