version: '3.8'

services:
  apiserver:
    build: ./apiserver
    networks:
      - backend

  web-front:
    build: ./web-front
    ports:
      - "80:80"
    networks:
      - backend
      - client
    depends_on:
      - apiserver

  clicker:
    build: ./clicker
    networks:
      - client
    depends_on:
      - web-front

networks:
  backend:
  client:
